version: '3.5'  
services: 
  mongo:
    image: mongo
    ports:
      - "27017:27107"
    volumes: 
      - /data/db:/data/db
    healthcheck:
      test: "echo 'db.stats().ok' | mongo localhost:27017 --quiet"
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks: 
      - fluentd-research

  fluentd-research:
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - "24284:24284"
    depends_on:
      - mongo
    volumes: 
      - ./src/output-to-mongodb:/fluentd/etc
    networks: 
      - fluentd-research
      
networks: 
  fluentd-research:
    name: fluentd-research

  
