version: '3'  
services: 
  mongo:
    image: mongo
    ports:
      - "27017:27107"
    volumes: 
      - /data/db:/data/db

  fluentd-research:
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - "24284:24284"
    depends_on:
      - mongo
    volumes: 
      - ./src/output-to-mongodb:/fluentd/etc
      


  
